job/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
 path('admin/', admin.site.urls),
 path('',include('website.urls')),
 path('dashboard/',include('dashboard.urls')),
 path('accounts/',include('users.urls')),
path('company/',include('company.urls')),
path('resume/',include('resume.urls')),
path('job/',include('jobcreate.urls'))

]
if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

jobcreate/models.py
from django.db import models
from users.models import User
from company.models import Company

class State(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name
    


class Industry(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name




class Job(models.Model):
    job_type_choices =(
        ('Remote','Remote'),
        ('Onsite','Onsite'),
        ('Hybrid','Hybrid')
    )
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    company = models.ForeignKey(Company,on_delete=models.CASCADE)
    title = models.CharField(max_length=100)
    location = models.CharField(max_length=100)
    salary = models.PositiveIntegerField(default=35000)
    requirments = models.TextField()
    ideal_candidate = models.TextField()
    is_available = models.BooleanField(default=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    industry = models.ForeignKey(Industry,on_delete=models.DO_NOTHING,null=True,blank=True)
    state = models.ForeignKey(State,on_delete=models.DO_NOTHING,null=True,blank=True)
    job_type = models.CharField(max_length=20,choices=job_type_choices,null=True,blank=True)
    

    def __str__(self):
        return self.title




class ApplyJob(models.Model):
    status_choices =(
        ('Accepted','Accepted'),
        ('Declined','Declined'),
        ('Pending','Pending')
    )
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    job = models.ForeignKey(Job,on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=20,choices=status_choices)

templates/job/all_applicants.html
{% extends "base.html" %} {% block content %}

<div class="card max-auto" style="width: 76rem">
  <div class="card-body">
    <h5 class="card-title mb-3">all Applicants for {{job.title}} Possiton</h5>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">First Name</th>
          <th scope="col">Surname</th>
          <th scope="col">Location</th>
          <th scope="col">Job Position</th>
          <th scope="col">Application Date</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for applicant in applicants %}
        <tr>
          <td>{{applicant.user.resume.first_name}}</td>
          <td>{{applicant.user.resume.surname}}</td>
          <td>{{applicant.user.resume.location}}</td>
          <td>{{applicant.user.resume.job_title}}</td>
          <td>{{applicant.timestamp}}</td>
          <td>
            <a href="{{applicant.user.resume.upload_resume.url}}"><small>Download Resume</small></a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}

templates/job/applied_job.html
{% extends "base.html" %} {% block content %}

<div class="card max-auto" style="width: 76rem">
  <div class="card-body">
    <h5 class="card-title mb-3">Applied Jobs</h5>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Job title</th>
          <th scope="col">Location</th>
          <th scope="col">Salary</th>
          <th scope="col">Job Type</th>
          <th scope="col">Industry</th>
         
        </tr>
      </thead>
      <tbody>
        {% for job in jobs %}
        <tr>
          <td>{{job.job.title}}</td>
          <td>{{job.job.location}}, {{job.job.state}}</td>
          <td>{{job.job.salary}}</td>
          <td>{{job.job.job_type}}</td>
          <td>{{job.job.industry}}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}

templates/job/create_job.html
{% extends "base.html" %} {% load widget_tweaks %} {% block content %}

<div class="row">
  <div class="col-md-6">
    <div class="card mx-auto" style="width: 40rem">
      <div class="card-body">
        <h5 class="card-title mb-3">Create A Job</h5>
        <form action="" method="POST">
          {% csrf_token %}
          <div class="mb-3">
            <label for="" class="form-label">Job title</label>
            {% render_field form.title class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Salary</label>
            {% render_field form.salary class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Location</label>
            {% render_field form.location class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">State</label>
            {% render_field form.state class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Industry</label>
            {% render_field form.industry class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Job Type</label>
            {% render_field form.job_type class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Job Requirements</label>
            {% render_field form.requirments|attr:"rows:2" class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Ideal Candidate</label>
            {% render_field form.ideal_candidate|attr:"rows:2" class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Is this Job Available</label>
            {% render_field form.is_available class="form-check-input"%}
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/job/manage_job.html
{% extends "base.html" %} {% block content %}

<div class="card max-auto" style="width: 76rem">
  <div class="card-body">
    <h5 class="card-title mb-3">Manage Jobs</h5>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">Job title</th>
          <th scope="col">Location</th>
          <th scope="col">Salary</th>
          <th scope="col">No of Applicants(Users)</th>
          <th scope="col">Status</th>
          <th scope="col">Action</th>
        </tr>
      </thead>
      <tbody>
        {% for job in jobs %}
        <tr>
          <td>{{job.title}}</td>
          <td>{{job.location}}</td>
          <td>{{job.salary}}</td>
          <td>{{job.applyjob_set.all.count}}<a href="{% url 'all-applicants' job.pk%}"><small>View All</small></a></td>
          {% if job.is_available %}
          <td><span class="badge bg-success">Active</span></td>
          {% else %}
          <td><span class="badge bg-warning">Not Active</span></td>
          {% endif %}
          <td>
            {% if perms.jobcreate.change_job %}
            <a href="{%url 'update-job' job.pk %}" class="btn btn-danger"><small>Update Job</small></a>
            {% endif %}
            {% if perms.jobcreate.delete_job %}
            <a href="{%url 'delete-job' job.pk %}" class="btn btn-dark"><small>delete Job</small></a>
            {% endif %}
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock content %}

templates/job/update_job.html
{% extends "base.html" %} {% load widget_tweaks %} {% block content %}

<div class="row">
  <div class="col-md-6">
    <div class="card mx-auto" style="width: 40rem">
      <div class="card-body">
        <h5 class="card-title mb-3">Update Job</h5>
        <form action="" method="POST">
          {% csrf_token %}
          <div class="mb-3">
            <label for="" class="form-label">Job title</label>
            {% render_field form.title class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Salary</label>
            {% render_field form.salary class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Location</label>
            {% render_field form.location class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">State</label>
            {% render_field form.state class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Industry</label>
            {% render_field form.industry class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Job Type</label>
            {% render_field form.job_type class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Job Requirements</label>
            {% render_field form.requirments|attr:"rows:2" class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Ideal Candidate</label>
            {% render_field form.ideal_candidate|attr:"rows:2" class="form-control"%}
          </div>
          <div class="mb-3">
            <label for="" class="form-label">Is this Job Available</label>
            {% render_field form.is_available class="form-check-input"%}
          </div>
          <button type="submit" class="btn btn-primary">Submit</button>
        </form>
      </div>
    </div>
  </div>
</div>

{% endblock content %}